server:
  port: 8091
 
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8091/eureka
    fetch-registry: false
    register-with-eureka: false
    
spring:
  devtools:
    restart:
      enabled: true
      additional-paths:
      - src/main/java
      - src/main/resources